/**
 * WeaponDemoScene — demonstrates the runtime weapon overlay system.
 *
 * Features:
 *   - WASD / arrow keys to move
 *   - Space to slash
 *   - 1-4 keys to select inventory slots directly
 *   - Q / E to cycle through equipped weapons
 *   - Walk into weapon pickups to auto-collect (up to 4)
 *   - HUD shows all 4 inventory slots with active highlight
 *
 * Assets expected in public/assets/sprites/ (generated by export_for_game.py):
 *   - char_0.png               — character spritesheet (preset 0)
 *   - weapon_<name>.png        — weapon spritesheets (4 orientations × 32px wide)
 *   - hand_anchors.json        — per-animation anchor data
 *
 * Weapon pickup sprites are just coloured circles until real pickup art is added.
 */

import Phaser from 'phaser'
import { EquippedPlayer, AnchorData } from '@/entities/EquippedPlayer'
import { INVENTORY_SIZE } from '@/systems/Inventory'

const CHAR_KEY = 'char_0'

// Weapons available in this demo (must have matching weapon_<name>.png)
const DEMO_WEAPONS = [
  'sword',
  'axe',
  'pistol',
  'bat',
]

// Pickup spawn positions (tile coordinates, multiplied by 48 for world coords)
const PICKUP_POSITIONS: Array<{ weapon: string; tx: number; ty: number }> = [
  { weapon: 'sword',  tx: 5,  ty: 5  },
  { weapon: 'axe',    tx: 12, ty: 5  },
  { weapon: 'pistol', tx: 5,  ty: 12 },
  { weapon: 'bat',    tx: 12, ty: 12 },
]

const TILE = 48  // world pixels per tile
const MAP_TILES = 20

// Pickup dot colours
const WEAPON_COLORS: Record<string, number> = {
  sword:  0xc0a060,
  axe:    0x8080ff,
  pistol: 0x808080,
  bat:    0x804020,
  spear:  0x60c080,
  staff:  0x8040c0,
  dagger: 0xc04040,
  mace:   0xa06040,
  bow:    0x80c040,
  greatsword: 0xff8040,
  shotgun:    0x606060,
  rifle:      0x506050,
  chain:      0xa0a0a0,
  molotov:    0xff6020,
  knife:      0xd0d0d0,
  taser:      0xffff40,
}

interface WeaponPickup {
  sprite:  Phaser.GameObjects.Arc
  weapon:  string
  label:   Phaser.GameObjects.Text
}

export class WeaponDemoScene extends Phaser.Scene {
  private player!: EquippedPlayer
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys
  private wasd!: {
    up: Phaser.Input.Keyboard.Key
    down: Phaser.Input.Keyboard.Key
    left: Phaser.Input.Keyboard.Key
    right: Phaser.Input.Keyboard.Key
  }
  private slashKey!: Phaser.Input.Keyboard.Key
  private slotKeys:  Phaser.Input.Keyboard.Key[] = []
  private cycleNext!: Phaser.Input.Keyboard.Key
  private cyclePrev!: Phaser.Input.Keyboard.Key

  private pickups:   WeaponPickup[] = []
  private hudSlots:  Phaser.GameObjects.Rectangle[] = []
  private hudIcons:  Phaser.GameObjects.Text[] = []
  private hudBorder: Phaser.GameObjects.Rectangle[] = []

  private anchorsLoaded = false

  constructor() {
    super({ key: 'WeaponDemoScene' })
  }

  preload(): void {
    // Character spritesheet — 128px wide × (5 anims × 4 dirs × 32px) tall = 640px
    this.load.spritesheet(CHAR_KEY, `assets/sprites/${CHAR_KEY}.png`, {
      frameWidth:  32,
      frameHeight: 32,
    })

    // Weapon spritesheets — 128px wide × 32px tall (4 orientations)
    for (const w of DEMO_WEAPONS) {
      this.load.spritesheet(`weapon_${w}`, `assets/sprites/weapon_${w}.png`, {
        frameWidth:  32,
        frameHeight: 32,
      })
    }

    // Hand anchor data
    this.load.json('hand_anchors', 'assets/sprites/hand_anchors.json')
  }

  create(): void {
    // ── World ────────────────────────────────────────────────────────────────
    this._createWorld()

    // ── Player ───────────────────────────────────────────────────────────────
    const cx = (MAP_TILES / 2) * TILE
    const cy = (MAP_TILES / 2) * TILE

    this.player = new EquippedPlayer(this, cx, cy, CHAR_KEY)
    this.player.createAnimations(CHAR_KEY)

    // Load anchor data
    const anchors = this.cache.json.get('hand_anchors') as AnchorData | null
    if (anchors) {
      this.player.setAnchors(anchors)
      this.anchorsLoaded = true
    }

    // Ensure weapon sprite is above the character
    this.children.bringToTop(this.player.weapon)

    // ── Pickups ───────────────────────────────────────────────────────────────
    this._createPickups()

    // ── Camera ────────────────────────────────────────────────────────────────
    this.cameras.main.setBounds(0, 0, MAP_TILES * TILE, MAP_TILES * TILE)
    this.cameras.main.startFollow(this.player.body, true, 0.1, 0.1)

    // ── Input ────────────────────────────────────────────────────────────────
    this.cursors = this.input.keyboard!.createCursorKeys()
    this.wasd = {
      up:    this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.W),
      down:  this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.S),
      left:  this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.A),
      right: this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.D),
    }
    this.slashKey  = this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE)
    this.cycleNext = this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.E)
    this.cyclePrev = this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.Q)

    for (let i = 0; i < INVENTORY_SIZE; i++) {
      this.slotKeys.push(
        this.input.keyboard!.addKey(
          (Phaser.Input.Keyboard.KeyCodes.ONE as number) + i
        )
      )
    }

    // ── HUD ──────────────────────────────────────────────────────────────────
    this._createHUD()

    // ── Help text ────────────────────────────────────────────────────────────
    const helpLines = [
      'WASD / Arrows — move',
      'Space — slash',
      '1-4 — select slot',
      'Q / E — cycle weapon',
      'Walk into pickup — collect',
    ]
    this.add.text(12, 12, helpLines.join('\n'), {
      fontSize: '11px',
      color: '#cccccc',
      backgroundColor: '#00000088',
      padding: { x: 6, y: 4 },
    }).setScrollFactor(0).setDepth(100)
  }

  update(): void {
    // ── Velocity ──────────────────────────────────────────────────────────────
    let vx = 0
    let vy = 0

    if (this.cursors.left.isDown  || this.wasd.left.isDown)  vx = -160
    if (this.cursors.right.isDown || this.wasd.right.isDown) vx =  160
    if (this.cursors.up.isDown    || this.wasd.up.isDown)    vy = -160
    if (this.cursors.down.isDown  || this.wasd.down.isDown)  vy =  160

    this.player.body.setVelocity(vx, vy)
    this.player.update(vx, vy)

    // ── Slash ─────────────────────────────────────────────────────────────────
    if (Phaser.Input.Keyboard.JustDown(this.slashKey)) {
      this.player.slash()
    }

    // ── Weapon cycle / select ─────────────────────────────────────────────────
    if (Phaser.Input.Keyboard.JustDown(this.cycleNext)) {
      this.player.inventory.cycleNext()
      this.player.equipWeapon(this.player.inventory.active)
    }
    if (Phaser.Input.Keyboard.JustDown(this.cyclePrev)) {
      this.player.inventory.cyclePrev()
      this.player.equipWeapon(this.player.inventory.active)
    }
    for (let i = 0; i < INVENTORY_SIZE; i++) {
      if (Phaser.Input.Keyboard.JustDown(this.slotKeys[i])) {
        this.player.inventory.selectSlot(i)
        this.player.equipWeapon(this.player.inventory.active)
      }
    }

    // ── Pickups ───────────────────────────────────────────────────────────────
    this._checkPickups()

    // ── HUD ───────────────────────────────────────────────────────────────────
    this._updateHUD()
  }

  // ── private helpers ────────────────────────────────────────────────────────

  private _createWorld(): void {
    const size = MAP_TILES * TILE
    const bg   = this.add.graphics()

    // Checkerboard grass
    for (let ty = 0; ty < MAP_TILES; ty++) {
      for (let tx = 0; tx < MAP_TILES; tx++) {
        const color = (tx + ty) % 2 === 0 ? 0x2a4a2a : 0x254525
        bg.fillStyle(color, 1)
        bg.fillRect(tx * TILE, ty * TILE, TILE, TILE)
      }
    }

    // Simple border walls (visual only — no physics in this demo)
    const border = this.add.graphics()
    border.lineStyle(4, 0x606060, 1)
    border.strokeRect(0, 0, size, size)

    // World bounds
    this.physics.world.setBounds(TILE, TILE, size - TILE * 2, size - TILE * 2)
  }

  private _createPickups(): void {
    for (const { weapon, tx, ty } of PICKUP_POSITIONS) {
      const wx = tx * TILE + TILE / 2
      const wy = ty * TILE + TILE / 2

      const color = WEAPON_COLORS[weapon] ?? 0xffffff
      const dot   = this.add.circle(wx, wy, 10, color).setDepth(1)

      const label = this.add.text(wx, wy + 14, weapon, {
        fontSize: '9px',
        color: '#eeeeee',
        backgroundColor: '#00000088',
        padding: { x: 2, y: 1 },
      }).setOrigin(0.5, 0).setDepth(1)

      this.pickups.push({ sprite: dot, weapon, label })
    }
  }

  private _checkPickups(): void {
    const px = this.player.body.x
    const py = this.player.body.y

    for (let i = this.pickups.length - 1; i >= 0; i--) {
      const p    = this.pickups[i]
      const dist = Phaser.Math.Distance.Between(px, py, p.sprite.x, p.sprite.y)

      if (dist < 28) {
        const slot = this.player.inventory.add(p.weapon)
        if (slot !== -1) {
          // First pickup — equip immediately
          if (this.player.inventory.snapshot.filter(s => s !== null).length === 1) {
            this.player.equipWeapon(p.weapon)
          }
          // Remove pickup from world
          p.sprite.destroy()
          p.label.destroy()
          this.pickups.splice(i, 1)
        }
      }
    }
  }

  private _createHUD(): void {
    const slotSize = 44
    const padding  = 6
    const startX   = 12
    const startY   = this.scale.height - slotSize - 12

    for (let i = 0; i < INVENTORY_SIZE; i++) {
      const x = startX + i * (slotSize + padding)

      const border = this.add.rectangle(x + slotSize / 2, startY + slotSize / 2,
        slotSize, slotSize, 0x000000, 0.6)
        .setStrokeStyle(2, 0x888888)
        .setScrollFactor(0)
        .setDepth(100)

      this.hudBorder.push(border)

      const slot = this.add.rectangle(x + slotSize / 2, startY + slotSize / 2,
        slotSize - 4, slotSize - 4, 0x222222, 0.8)
        .setScrollFactor(0)
        .setDepth(101)

      this.hudSlots.push(slot)

      const icon = this.add.text(x + slotSize / 2, startY + slotSize / 2, '', {
        fontSize: '10px',
        color: '#ffffff',
      }).setOrigin(0.5).setScrollFactor(0).setDepth(102)

      this.hudIcons.push(icon)

      // Slot number label
      this.add.text(x + 3, startY + 2, `${i + 1}`, {
        fontSize: '9px',
        color: '#aaaaaa',
      }).setScrollFactor(0).setDepth(103)
    }
  }

  private _updateHUD(): void {
    const snap   = this.player.inventory.snapshot
    const active = this.player.inventory.activeIndex

    for (let i = 0; i < INVENTORY_SIZE; i++) {
      const isActive = i === active && snap[i] !== null
      this.hudBorder[i].setStrokeStyle(2, isActive ? 0xffdd44 : 0x888888)
      this.hudSlots[i].setFillStyle(isActive ? 0x443300 : 0x222222, 0.8)
      this.hudIcons[i].setText(snap[i] ? snap[i]!.substring(0, 6) : '')
    }
  }
}
